x-faraday-image: &faraday-image faraday-local:latest
x-faraday-volumes: &faraday-volumes
  - "faraday:/home/faraday/.faraday:rw"

networks:
  proxy:
    external: true
  faradaynet:
    name: faradaynet

services:
  db:
    image: postgres:12.7-alpine
    container_name: faraday_db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=faraday
    volumes:
      - "db:/var/lib/postgresql/data:rw"
    networks: [faradaynet]

  redis:
    image: redis:8.4-alpine
    container_name: faraday_redis
    restart: always
    networks: [faradaynet]

  change-password:
    image: *faraday-image
    profiles: ["manual"]
    command: ["faraday-manage", "change-password"]
    volumes: *faraday-volumes
    networks: [faradaynet]
    depends_on: [db]

  faraday-manage:
    image: *faraday-image
    profiles: ["manual"]
    command: ["faraday-manage"]
    volumes: *faraday-volumes
    networks: [faradaynet]
    depends_on: [db]

  faraday-server:
    build:
      context: .
      # args:
      #   - DEV_ENV=1
    image: *faraday-image
    container_name: faraday_server
    restart: always
    entrypoint: "/entrypoint.sh"
    volumes: *faraday-volumes
    environment:
      - PGSQL_USER=postgres
      - PGSQL_PASSWD=postgres
      - PGSQL_HOST=db
      - PGSQL_DBNAME=faraday
      - REDIS_SERVER=redis
    depends_on: [db, redis]
    networks:
      faradaynet: {}
      proxy:
        ipv4_address: 172.19.0.11
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5985/_api/config"]
      interval: 20s
      timeout: 5s
      retries: 10
    labels:
      - traefik.enable=true
      - traefik.docker.network=proxy
      - traefik.http.routers.faraday.rule=Host(`faraday.arthurbidet.fr`)
      - traefik.http.routers.faraday.entrypoints=https
      - traefik.http.routers.faraday.tls=true
      - traefik.http.routers.faraday.tls.certresolver=production
      - traefik.http.routers.faraday.middlewares=authelia@docker

      - traefik.http.routers.faraday-api.rule=Host(`faraday.arthurbidet.fr`) && (PathPrefix(`/_api/`) || PathPrefix(`/socket.io`) || PathPrefix(`/websockets`))
      - traefik.http.routers.faraday-api.entrypoints=https
      - traefik.http.routers.faraday-api.tls=true
      - traefik.http.routers.faraday-api.tls.certresolver=production
      - traefik.http.routers.faraday-api.priority=100
      - traefik.http.routers.faraday-api.service=faraday
      
      - traefik.http.services.faraday.loadbalancer.server.port=5985

  faraday-default-worker:
    image: *faraday-image
    container_name: faraday_worker
    restart: always
    command: ["faraday-worker"]
    volumes: *faraday-volumes
    environment:
      - PGSQL_USER=postgres
      - PGSQL_PASSWD=postgres
      - PGSQL_HOST=db
      - PGSQL_DBNAME=faraday
      - REDIS_SERVER=redis
    networks: [faradaynet]
    depends_on:
      faraday-server:
        condition: service_healthy

volumes:
  db:
    driver: local
  faraday:
    driver: local
